CREATE TABLE [dbo].[Conciliacion_Manual] (
    [id_conciliacion_manual]            INT             NOT NULL,
    [id_transaccion]                    CHAR (36)       NULL,
    [importe]                           DECIMAL (12, 2) NULL,
    [moneda]                            INT             NULL,
    [cantidad_cuotas]                   INT             NULL,
    [nro_tarjeta]                       VARCHAR (50)    NULL,
    [codigo_barra]                      VARCHAR (50)    NULL,
    [fecha_movimiento]                  DATETIME        NULL,
    [nro_autorizacion]                  VARCHAR (50)    NULL,
    [nro_cupon]                         VARCHAR (50)    NULL,
    [nro_agrupador_boton]               VARCHAR (50)    NULL,
    [flag_aceptada_marca]               BIT             NULL,
    [flag_contracargo]                  BIT             NULL,
    [flag_conciliado_manual]            BIT             NOT NULL,
    [flag_procesado]                    BIT             NOT NULL,
    [fecha_alta]                        DATETIME        NULL,
    [usuario_alta]                      VARCHAR (20)    NULL,
    [fecha_modificacion]                DATETIME        NULL,
    [usuario_modificacion]              VARCHAR (20)    NULL,
    [fecha_baja]                        DATETIME        NULL,
    [usuario_baja]                      VARCHAR (20)    NULL,
    [version]                           INT             CONSTRAINT [DF_Conciliacion_Manual_version] DEFAULT ((0)) NOT NULL,
    [cargos_boton_por_movimiento]       DECIMAL (12, 2) NULL,
    [impuestos_boton_por_movimiento]    DECIMAL (12, 2) NULL,
    [cargos_marca_por_movimiento]       DECIMAL (12, 2) NULL,
    [fecha_pago]                        DATETIME        NULL,
    [id_log_paso]                       INT             NULL,
    [signo_cargos_marca_por_movimiento] VARCHAR (1)     NULL,
    [id_movimiento_mp]                  INT             NULL,
    [id_motivo_conciliacion_manual]     INT             NULL,
    CONSTRAINT [PK_Conciliacion_Manual] PRIMARY KEY CLUSTERED ([id_conciliacion_manual] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_Conciliacion_Manual_Motivo_Conciliacion_Manual] FOREIGN KEY ([id_motivo_conciliacion_manual]) REFERENCES [dbo].[Motivo_Conciliacion_Manual] ([id_motivo_conciliacion_manual]),
    CONSTRAINT [FK_Conciliacion_Manual_Movimiento_Presentado_MP] FOREIGN KEY ([id_movimiento_mp]) REFERENCES [dbo].[Movimiento_Presentado_MP] ([id_movimiento_mp])
);

