CREATE TABLE [dbo].[Info_archivo_abm_cuenta_Tmp] (
    [id_detalle]      INT           NOT NULL,
    [detalle]         VARCHAR (MAX) NOT NULL,
    [nombre_archivo]  VARCHAR (150) NOT NULL,
    [Cod_solicitante] VARCHAR (20)  NULL,
    [Nro_solicitante] INT           NULL,
    [Tipo_novedad]    CHAR (1)      NULL,
    [Tipo_Cuenta]     VARCHAR (20)  NULL,
    [E_Mail]          VARCHAR (50)  NULL,
    [Nom_Fantasia]    VARCHAR (50)  NULL,
    [Razon_Social]    VARCHAR (50)  NULL,
    [Nombre]          VARCHAR (50)  NULL,
    [Apellido]        VARCHAR (50)  NULL,
    [Id_Genero]       CHAR (1)      NULL,
    [Id_Nacionalidad] INT           NULL,
    [Id_Tipo_Doc]     VARCHAR (3)   NULL,
    [Nro_Doc]         VARCHAR (12)  NULL,
    [fec_nac]         CHAR (8)      NULL,
    [Op_Celular]      INT           NULL,
    [Nro_Celular]     VARCHAR (10)  NULL,
    [Nro_Telefono]    VARCHAR (10)  NULL,
    [Cond_IVA]        VARCHAR (20)  NULL,
    [Cond_IIBB]       VARCHAR (20)  NULL,
    [Actividad]       VARCHAR (4)   NULL,
    [CUIT]            VARCHAR (11)  NULL,
    [Calle_Legal]     VARCHAR (30)  NULL,
    [Nro_Legal]       VARCHAR (10)  NULL,
    [Piso_Legal]      VARCHAR (10)  NULL,
    [Depto_Legal]     VARCHAR (10)  NULL,
    [Cod_Post_Legal]  VARCHAR (8)   NULL,
    [Id_Prov_Legal]   INT           NULL,
    [Loc_Legal]       VARCHAR (4)   NULL,
    [Calle_Fact]      VARCHAR (30)  NULL,
    [Nro_Fact]        VARCHAR (10)  NULL,
    [Piso_Fact]       VARCHAR (10)  NULL,
    [Depto_Fact]      VARCHAR (10)  NULL,
    [Cod_Post_Fact]   VARCHAR (8)   NULL,
    [Id_Prov_Fact]    INT           NULL,
    [Loc_Fact]        VARCHAR (4)   NULL,
    [CBU]             VARCHAR (22)  NULL,
    [Tipo_cashout]    VARCHAR (20)  NULL,
    [Cant_Mpos]       INT           NULL,
    [Costo_Mpos]      VARCHAR (20)  NULL,
    [Canal]           INT           NULL,
    [Acepta_TyC]      CHAR (1)      NULL
);

