CREATE TABLE [dbo].[Movimientos_a_distribuir] (
    [id_transaccion]                              CHAR (36)       NULL,
    [tipo]                                        VARCHAR (1)     CONSTRAINT [DF_Movimientos_a_distribuir_tipo] DEFAULT ('M') NULL,
    [id_medio_pago]                               INT             NULL,
    [id_cuenta]                                   INT             NULL,
    [BCRA_cuenta]                                 INT             NULL,
    [BCRA_emisor_tarjeta]                         INT             NULL,
    [signo_importe]                               CHAR (1)        NULL,
    [importe]                                     DECIMAL (12, 2) NULL,
    [signo_cargo_marca]                           CHAR (1)        NULL,
    [cargo_marca]                                 DECIMAL (12, 2) NULL,
    [signo_cargo_boton]                           CHAR (1)        NULL,
    [cargo_boton]                                 DECIMAL (12, 2) NULL,
    [signo_impuesto_boton]                        CHAR (1)        NULL,
    [impuesto_boton]                              DECIMAL (12, 2) NULL,
    [fecha_liberacion_cashout]                    DATETIME        NULL,
    [id_log_paso]                                 INT             NULL,
    [flag_esperando_impuestos_generales_de_marca] BIT             NULL,
    [fecha_alta]                                  DATETIME        NOT NULL,
    [usuario_alta]                                VARCHAR (20)    NOT NULL,
    [fecha_modificacion]                          DATETIME        NULL,
    [usuario_modificacion]                        VARCHAR (20)    NULL,
    [fecha_baja]                                  DATETIME        NULL,
    [usuario_baja]                                VARCHAR (20)    NULL,
    [version]                                     INT             CONSTRAINT [DF_MAD_version] DEFAULT ((0)) NOT NULL,
    [id_movimiento_mp]                            INT             NULL,
    CONSTRAINT [FK_MaD_Mov_Pres_MP] FOREIGN KEY ([id_movimiento_mp]) REFERENCES [dbo].[Movimiento_Presentado_MP] ([id_movimiento_mp]),
    CONSTRAINT [FK_TMP_Movimientos_A_Distribuir_Medio_de_pago] FOREIGN KEY ([id_medio_pago]) REFERENCES [dbo].[Medio_De_Pago] ([id_medio_pago])
);

