CREATE TABLE [dbo].[Cliente_Unico_Relacion] (
    [id_cliente_unico_relacion] INT           NOT NULL,
    [tipo_identificacion]       VARCHAR (20)  NULL,
    [numero_identificacion]     VARCHAR (20)  NULL,
    [sexo]                      VARCHAR (1)   NULL,
    [banco]                     VARCHAR (3)   NULL,
    [id_medio_pago]             INT           NULL,
    [nombre]                    VARCHAR (50)  NULL,
    [numero_tarjeta]            VARCHAR (256) NOT NULL,
    [fecha_vencimiento]         VARCHAR (6)   NULL,
    [fecha_nacimiento]          DATETIME      NULL,
    [numero_cuit]               VARCHAR (11)  NULL,
    [telefono_movil]            VARCHAR (10)  NULL,
    [telefono_fijo]             VARCHAR (10)  NULL,
    [calle]                     VARCHAR (30)  NULL,
    [numero]                    VARCHAR (10)  NULL,
    [piso]                      VARCHAR (10)  NULL,
    [departamento]              VARCHAR (10)  NULL,
    [id_provincia]              INT           NULL,
    [codigo_postal]             VARCHAR (20)  NULL,
    [nacionalidad]              VARCHAR (20)  NULL,
    [fecha_alta]                DATETIME      NOT NULL,
    [usuario_alta]              VARCHAR (20)  NOT NULL,
    [fecha_modificacion]        DATETIME      NULL,
    [usuario_modificacion]      VARCHAR (20)  NULL,
    [fecha_baja]                DATETIME      NULL,
    [usuario_baja]              VARCHAR (20)  NULL,
    [version]                   INT           DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([id_cliente_unico_relacion] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_Cliente_Unico_Relacion_Banco] FOREIGN KEY ([banco]) REFERENCES [dbo].[Banco] ([codigo]),
    CONSTRAINT [FK_Cliente_Unico_Relacion_Medio_De_Pago] FOREIGN KEY ([id_medio_pago]) REFERENCES [dbo].[Medio_De_Pago] ([id_medio_pago]),
    CONSTRAINT [FK_Cliente_Unico_Relacion_Provincia] FOREIGN KEY ([id_provincia]) REFERENCES [dbo].[Provincia] ([id_provincia]),
    CONSTRAINT [FK_Cliente_Unico_Relacion_Tipo] FOREIGN KEY ([tipo_identificacion]) REFERENCES [dbo].[Tipo] ([codigo])
);

