CREATE TABLE [dbo].[Disputa] (
    [id_disputa]                  INT           IDENTITY (1, 1) NOT NULL,
    [id_tipo_origen]              INT           NOT NULL,
    [id_transaccion]              CHAR (36)     NOT NULL,
    [id_transaccion_cuenta]       VARCHAR (64)  NOT NULL,
    [id_medio_pago]               INT           NOT NULL,
    [fecha_notificacion_mp]       DATE          NOT NULL,
    [fecha_vencimiento_mp]        DATE          NOT NULL,
    [fecha_resolucion_mp]         DATE          NULL,
    [id_estado_resolucion_mp]     INT           NOT NULL,
    [id_cuenta]                   INT           NOT NULL,
    [fecha_notificacion_cuenta]   DATETIME      NULL,
    [fecha_vencimiento_cuenta]    DATETIME      NULL,
    [fecha_resolucion_cuenta]     DATETIME      NULL,
    [id_estado_resolucion_cuenta] INT           NULL,
    [fecha_alta]                  DATETIME      NULL,
    [usuario_alta]                VARCHAR (20)  NULL,
    [fecha_modificacion]          DATETIME      NULL,
    [usuario_modificacion]        VARCHAR (20)  NULL,
    [fecha_baja]                  DATETIME      NULL,
    [usuario_baja]                VARCHAR (20)  NULL,
    [version]                     INT           CONSTRAINT [DF_Disputa_version] DEFAULT ((0)) NOT NULL,
    [motivo_resolucion_cuenta]    VARCHAR (256) NULL,
    [id_log_proceso]              INT           NULL,
    [usuario_resolucion]          VARCHAR (20)  NULL,
    [id_motivo_estado]            INT           DEFAULT (NULL) NULL,
    [id_notificacion_enviada]     INT           NULL,
    CONSTRAINT [PK_id_disputa] PRIMARY KEY CLUSTERED ([id_disputa] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_disputa_id_cuenta] FOREIGN KEY ([id_cuenta]) REFERENCES [dbo].[Cuenta] ([id_cuenta]),
    CONSTRAINT [FK_disputa_id_estado_resolucion_cuenta] FOREIGN KEY ([id_estado_resolucion_cuenta]) REFERENCES [dbo].[Estado] ([id_estado]),
    CONSTRAINT [FK_disputa_id_estado_resolucion_mp] FOREIGN KEY ([id_estado_resolucion_mp]) REFERENCES [dbo].[Estado] ([id_estado]),
    CONSTRAINT [FK_disputa_id_medio_pago] FOREIGN KEY ([id_medio_pago]) REFERENCES [dbo].[Medio_De_Pago] ([id_medio_pago]),
    CONSTRAINT [FK_Disputa_Id_Motivo_Estado] FOREIGN KEY ([id_motivo_estado]) REFERENCES [dbo].[Motivo_Estado] ([id_motivo_estado]),
    CONSTRAINT [FK_disputa_id_tipo_origen] FOREIGN KEY ([id_tipo_origen]) REFERENCES [dbo].[Tipo] ([id_tipo]),
    CONSTRAINT [FK_doc_disputa_id_disputa] FOREIGN KEY ([id_disputa]) REFERENCES [dbo].[Disputa] ([id_disputa]),
    CONSTRAINT [FK_NotificacionEnviada_IdNotificacion] FOREIGN KEY ([id_notificacion_enviada]) REFERENCES [dbo].[Notificacion_Enviada] ([id_notificacion_enviada])
);

