CREATE TABLE [dbo].[Movimientos_a_Conciliar_tmp] (
    [id]                                INT             IDENTITY (1, 1) NOT NULL,
    [id_movimiento_mp]                  INT             NULL,
    [id_transaccion]                    VARCHAR (36)    NULL,
    [id_medio_pago]                     INT             NULL,
    [importe]                           DECIMAL (12, 2) NULL,
    [signo_importe]                     CHAR (1)        NULL,
    [moneda]                            INT             NULL,
    [cantidad_cuotas]                   INT             NULL,
    [nro_tarjeta]                       VARCHAR (50)    NULL,
    [codigo_barra]                      VARCHAR (128)   NULL,
    [fecha_movimiento]                  DATETIME        NULL,
    [nro_autorizacion]                  VARCHAR (8)     NULL,
    [nro_cupon]                         INT             NULL,
    [cargos_marca_por_movimiento]       DECIMAL (12, 2) NULL,
    [signo_cargos_marca_por_movimiento] CHAR (1)        NULL,
    [cargos_boton_por_movimiento]       DECIMAL (12, 2) NULL,
    [impuestos_boton_por_movimiento]    DECIMAL (12, 2) NULL,
    [nro_agrupador_boton]               VARCHAR (50)    NULL,
    [fecha_pago]                        DATETIME        NULL,
    [mask_nro_tarjeta]                  VARCHAR (20)    NULL,
    [hash_nro_tarjeta]                  VARCHAR (80)    NULL,
    [codigo]                            VARCHAR (20)    NULL,
    [flag_contracargo]                  BIT             NULL,
    [flag_aceptada_marca]               BIT             NULL,
    [id_disputa]                        INT             NULL,
    [flag_notificado]                   BIT             NULL,
    [cant_tx]                           INT             DEFAULT ((0)) NULL,
    [estado_cupon]                      VARCHAR (50)    NULL,
    [estado_tx]                         VARCHAR (20)    NULL,
    PRIMARY KEY CLUSTERED ([id] ASC)
);

