CREATE TABLE [dbo].[Promocion] (
    [id_promocion]              INT           IDENTITY (1, 1) NOT NULL,
    [nombre]                    VARCHAR (50)  NOT NULL,
    [descripcion]               VARCHAR (100) NULL,
    [cant_cuotas_desde]         INT           NOT NULL,
    [cant_cuotas_hasta]         INT           NOT NULL,
    [fecha_inicio_vigencia]     DATE          NOT NULL,
    [fecha_fin_vigencia]        DATE          NOT NULL,
    [fecha_alta]                DATETIME      NULL,
    [usuario_alta]              VARCHAR (20)  NULL,
    [fecha_modificacion]        DATETIME      NULL,
    [usuario_modificacion]      VARCHAR (20)  NULL,
    [fecha_baja]                DATETIME      NULL,
    [usuario_baja]              VARCHAR (20)  NULL,
    [version]                   INT           CONSTRAINT [DF_Promocion_version] DEFAULT ((0)) NOT NULL,
    [id_medio_pago]             INT           NULL,
    [id_banco]                  INT           NULL,
    [id_cuenta]                 INT           NULL,
    [id_rubro]                  INT           NULL,
    [flag_aplica_lunes]         BIT           CONSTRAINT [DF_Promocion_flag_activa_lunes] DEFAULT ((0)) NOT NULL,
    [flag_aplica_martes]        BIT           CONSTRAINT [DF_Promocion_flag_activa_martes] DEFAULT ((0)) NOT NULL,
    [flag_aplica_miercoles]     BIT           CONSTRAINT [DF_Promocion_flag_activa_miercoles] DEFAULT ((0)) NOT NULL,
    [flag_aplica_jueves]        BIT           CONSTRAINT [DF_Promocion_flag_activa_jueves] DEFAULT ((0)) NOT NULL,
    [flag_aplica_viernes]       BIT           CONSTRAINT [DF_Promocion_flag_activa_viernes] DEFAULT ((0)) NOT NULL,
    [flag_aplica_sabado]        BIT           CONSTRAINT [DF_Promocion_flag_activa_sabado] DEFAULT ((0)) NOT NULL,
    [flag_aplica_domingo]       BIT           CONSTRAINT [DF_Promocion_flag_activa_domingo] DEFAULT ((0)) NOT NULL,
    [bonificacion_cf_comprador] BIT           CONSTRAINT [DF_Promocion_bonificacion_cf_comprador] DEFAULT ((0)) NOT NULL,
    [id_motivo_estado]          INT           NULL,
    [id_estado_procesamiento]   INT           NOT NULL,
    [id_tipo_aplicacion]        INT           NOT NULL,
    CONSTRAINT [PK_Promocion] PRIMARY KEY CLUSTERED ([id_promocion] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_Promocion_estado_procesamiento] FOREIGN KEY ([id_estado_procesamiento]) REFERENCES [dbo].[Estado] ([id_estado]),
    CONSTRAINT [FK_Promocion_id_banco] FOREIGN KEY ([id_banco]) REFERENCES [dbo].[Banco] ([id_banco]),
    CONSTRAINT [FK_Promocion_id_cuenta] FOREIGN KEY ([id_cuenta]) REFERENCES [dbo].[Cuenta] ([id_cuenta]),
    CONSTRAINT [FK_Promocion_id_medio_pago] FOREIGN KEY ([id_medio_pago]) REFERENCES [dbo].[Medio_De_Pago] ([id_medio_pago]),
    CONSTRAINT [FK_Promocion_id_rubro] FOREIGN KEY ([id_rubro]) REFERENCES [dbo].[Rubro] ([id_rubro]),
    CONSTRAINT [FK_Promocion_id_tipo_aplicacion] FOREIGN KEY ([id_tipo_aplicacion]) REFERENCES [dbo].[Tipo] ([id_tipo]),
    CONSTRAINT [FK_Promocion_motivo_estado] FOREIGN KEY ([id_motivo_estado]) REFERENCES [dbo].[Motivo_Estado] ([id_motivo_estado]),
    CONSTRAINT [FK_Promocion_Tipo] FOREIGN KEY ([id_tipo_aplicacion]) REFERENCES [dbo].[Tipo] ([id_tipo])
);

