CREATE TABLE [dbo].[Hist_Estado_Cuenta] (
    [id_cuenta]                    INT          NOT NULL,
    [id_tipo_cuenta]               INT          NOT NULL,
    [denominacion1]                VARCHAR (50) NOT NULL,
    [denominacion2]                VARCHAR (50) NOT NULL,
    [id_tipo_identificacion]       INT          NULL,
    [numero_identificacion]        VARCHAR (20) NULL,
    [numero_CUIT]                  VARCHAR (11) NULL,
    [sexo]                         VARCHAR (1)  NULL,
    [id_nacionalidad]              INT          NULL,
    [fecha_nacimiento]             DATETIME     NULL,
    [id_canal]                     INT          NOT NULL,
    [id_estado_cuenta]             INT          NOT NULL,
    [id_version_tyc]               INT          NULL,
    [flag_envio_novedades]         BIT          NULL,
    [fecha_alta]                   DATETIME     NULL,
    [usuario_alta]                 VARCHAR (20) NULL,
    [fecha_modificacion]           DATETIME     NULL,
    [usuario_modificacion]         VARCHAR (20) NULL,
    [fecha_baja]                   DATETIME     NULL,
    [usuario_baja]                 VARCHAR (20) NULL,
    [version]                      INT          NOT NULL,
    [telefono_movil]               VARCHAR (10) NULL,
    [telefono_fijo]                VARCHAR (10) NULL,
    [flag_cambio_pendiente]        BIT          NULL,
    [flag_informado_a_facturacion] BIT          NULL,
    [id_operador_celular]          INT          NULL,
    [id_banco_adhesion]            INT          NULL,
    [flag_factor_validacion]       BIT          NULL,
    [flag_envio_mail]              INT          NULL
);

