CREATE TABLE [dbo].[Transacciones_P2P] (
    [id_p2p]                      INT             IDENTITY (1, 1) NOT NULL,
    [id_cuenta_origen]            INT             NOT NULL,
    [id_mp_cuenta]                INT             NOT NULL,
    [id_cuenta_destino]           INT             NOT NULL,
    [monto]                       DECIMAL (12, 2) NOT NULL,
    [mensaje]                     VARCHAR (100)   DEFAULT (NULL) NULL,
    [id_transaccion]              VARCHAR (36)    NOT NULL,
    [id_estado_p2p]               INT             NOT NULL,
    [id_canal]                    INT             NULL,
    [mail_destino]                VARCHAR (50)    NULL,
    [nrocelular_destino]          VARCHAR (10)    NULL,
    [id_tipo_transaccion]         INT             NOT NULL,
    [fecha_alta]                  DATETIME        NULL,
    [usuario_alta]                VARCHAR (20)    NULL,
    [fecha_modificacion]          DATETIME        NULL,
    [usuario_modificacion]        VARCHAR (20)    NULL,
    [fecha_baja]                  DATETIME        NULL,
    [usuario_baja]                VARCHAR (20)    NULL,
    [version]                     INT             NOT NULL,
    [fecha_liberacion]            DATETIME        DEFAULT (NULL) NULL,
    [fecha_afectacion_saldo]      DATETIME        DEFAULT (NULL) NULL,
    [flag_afectacion_saldo]       BIT             DEFAULT ((0)) NULL,
    [fecha_afectacion_fondeo]     DATETIME        DEFAULT (NULL) NULL,
    [flag_afectacion_fondeo]      BIT             DEFAULT ((0)) NULL,
    [fecha_afectacion_disponible] DATETIME        DEFAULT (NULL) NULL,
    [flag_afectacion_disponible]  BIT             DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([id_p2p] ASC),
    FOREIGN KEY ([id_canal]) REFERENCES [dbo].[Canal_Adhesion] ([id_canal]),
    FOREIGN KEY ([id_cuenta_destino]) REFERENCES [dbo].[Cuenta] ([id_cuenta]),
    FOREIGN KEY ([id_cuenta_origen]) REFERENCES [dbo].[Cuenta] ([id_cuenta]),
    FOREIGN KEY ([id_estado_p2p]) REFERENCES [dbo].[Estado] ([id_estado]),
    FOREIGN KEY ([id_mp_cuenta]) REFERENCES [dbo].[Medio_Pago_Cuenta] ([id_medio_pago_cuenta]),
    FOREIGN KEY ([id_tipo_transaccion]) REFERENCES [dbo].[Tipo_Transaccion] ([id_tipo_transaccion])
);

