
CREATE PROCEDURE [dbo].[Batch_Sincronizacion_Op_Tx]
AS
DECLARE @registros_afectados INT;
DECLARE @msg VARCHAR(50);
DECLARE @id_proceso INT = 17;
DECLARE @id_log_proceso INT;
DECLARE @id_nivel_detalle_global INT;
DECLARE @nombre_sp VARCHAR(50);
DECLARE @usuario VARCHAR(20) = 'bpbatch';
DECLARE @MergeTable TABLE (srcId VARCHAR(36));

SET NOCOUNT ON;

BEGIN TRY
	BEGIN TRANSACTION;

	SET @nombre_sp = OBJECT_NAME(@@PROCID);

	-- Iniciar Log     
	EXEC Configurations.dbo.Batch_Log_Iniciar_Proceso @id_proceso,
		NULL,
		NULL,
		@Usuario,
		@id_log_proceso = @id_log_proceso OUTPUT,
		@id_nivel_detalle_global = @id_nivel_detalle_global OUTPUT;

	-- Sincronizar Transacciones
	MERGE Transactions.dbo.transactions AS trg
	USING (
		SELECT Id,
			CreateTimestamp,
			UpdateTimestamp,
			TransportTimestamp,
			RequestInputTimestamp,
			RequestOutputTimestamp,
			AnswerInputTimestamp,
			AnswerOutputTimestamp,
			DeviceIdentification,
			LocationIdentification,
			ServiceName,
			OperationName,
			SequenceNumber,
			STATUS,
			UserIdentification,
			ProviderIdentification,
			ProviderTransactionID,
			DeviceTransactionID,
			SyncStatus,
			SyncTimestamp,
			ProductIdentification,
			RetrievalReferenceNumber,
			FacilitiesPayments,
			FacilitiesType,
			CurrencyCode,
			Amount,
			FeeAmount,
			TaxAmount,
			ComissionAmount,
			ServiceChargeAmount,
			MerchantIdentification,
			ProviderDeviceIdentification,
			ReverseStatus,
			ReverseTimestamp,
			VoidStatus,
			VoidTimestamp,
			VoidUserIdentification,
			RefundStatus,
			RefundTimestamp,
			RefundUserIdentification,
			RefundAmount,
			CloseStatus,
			CloseTimestamp,
			CloseUserIdentification,
			SettlementStatus,
			SettlementTimestamp,
			SettlementUserIdentification,
			SettlementAmount,
			SettlementTransactionId,
			RevisionStatus,
			RevisionTimestamp,
			RevisionReason,
			RevisionSource,
			BatchNumber,
			TicketNumber,
			ProviderBatchNumber,
			ProviderTicketNumber,
			ProviderTraceNumber,
			ProviderAuthorizationCode,
			CustomerIdentification,
			CredentialInputMode,
			CredentialMask,
			CredentialEncrypted,
			CredentialExpDate,
			CredentialCardHash,
			CredentialHolderName,
			CredentialAddress,
			CredentialDocumentType,
			CredentialDocumentNumber,
			CredentialEmailAddress,
			DeviceFingerprint,
			ResultCode,
			ResultMessage,
			ProviderResultCode,
			ProviderResultMessage,
			Channel,
			CaptureAddress,
			CaptureTimestamp,
			RequestAddress,
			RequestTimestamp,
			AnswerAddress,
			AnswerTimestamp,
			RedirectURLOK,
			RedirectURLError,
			CredentialBirthday,
			BillHolderName,
			BillHolderDocumentType,
			BillHolderDocumentNumber,
			ProviderCustomerCode,
			ProviderCustomerAdditionalCode,
			ChargeLatePaymentAmount,
			DifferenceBetweenFirstExpiration,
			DaysAfterFirstExpiration,
			CouponExpirationDate,
			InvoiceExpirationDate,
			PaymentBarCode,
			InvoiceBarCode,
			LiquidationStatus,
			LiquidationTimestamp,
			ReconciliationStatus,
			ReconciliationTimestamp,
			AvailableStatus,
			AvailableTimestamp,
			AvailableAmount,
			BillingStatus,
			BillingTimestamp,
			ProcessorResultCode,
			ProcessorResultMessage,
			ButtonId,
			ButtonExternalId,
			ButtonMinimumAmount,
			ButtonMaximumAmount,
			SaleConcept,
			MerchantActivityCode,
			ChargebackStatus,
			ChargebackTimestamp,
			ChargebackReason,
			CashoutStatus,
			CashoutTimestamp,
			FilingDeadline,
			PaymentDeadline,
			PaymentTimestamp,
			PaymentStatus,
			CouponStatus,
			CouponDaysBetweenExpDates,
			CouponValidityDays,
			CouponFee,
			CouponSecondExpirationDate,
			CouponClientCode,
			CouponSubscriber,
			CouponOperationId,
			OriginalOperationId,
			TransactionStatus,
			ProductType,
			BankIdentification,
			BuyerAccountIdentification,
			PrivateRequestKey,
			PublicRequestKey,
			PrivateAnswerKey,
			PublicAnswerKey,
			PublicIdentification,
			id_medio_pago_cuenta,
			AmountBuyer,
			FeeAmountBuyer,
			TaxAmountBuyer,
			PromotionIdentification,
			AdditionalData,
			FraudResultCode,
			FraudTransactionID,
			PresentationTimestamp,
			DocumentationTimestamp,
			DocumentationURL,
			PushNotifyMethod,
			PushNotifyEndpoint,
			PushNotifyStates,
			PushNotifySentTimestamp,
			PushNotifyCounter,
			Version,
			BuyerIP,
			SDK,
			SDKVersion,
			LenguageVersion,
			PluginVersion,
			ECommerceName,
			ECommerceVersion,
			CMSVersion,
			flag_formulario_cargado,
			CashoutReleaseStatus,
			CashoutReleaseTimestamp,
			MaxInstallments
		FROM Operations.dbo.transactions
		WHERE SyncStatus = 0
		) AS src
		ON (trg.Id = src.Id)
	WHEN MATCHED
		THEN
			UPDATE
			SET trg.AdditionalData = src.AdditionalData,
				trg.AmountBuyer = src.AmountBuyer,
				trg.BankIdentification = src.BankIdentification,
				trg.BuyerAccountIdentification = src.BuyerAccountIdentification,
				trg.CloseStatus = src.CloseStatus,
				trg.CloseTimestamp = src.CloseTimestamp,
				trg.CloseUserIdentification = src.CloseUserIdentification,
				trg.id_medio_pago_cuenta = src.id_medio_pago_cuenta,
				trg.PrivateAnswerKey = src.PrivateAnswerKey,
				trg.PrivateRequestKey = src.PrivateRequestKey,
				trg.ProductType = src.ProductType,
				trg.PromotionIdentification = src.PromotionIdentification,
				trg.PublicAnswerKey = src.PublicAnswerKey,
				trg.PublicIdentification = src.PublicIdentification,
				trg.PublicRequestKey = src.PublicRequestKey,
				trg.PushNotifyCounter = src.PushNotifyCounter,
				trg.PushNotifySentTimestamp = src.PushNotifySentTimestamp,
				trg.RefundAmount = src.RefundAmount,
				trg.RefundStatus = src.RefundStatus,
				trg.RefundTimestamp = src.RefundTimestamp,
				trg.RefundUserIdentification = src.RefundUserIdentification,
				trg.VoidStatus = src.VoidStatus,
				trg.VoidTimestamp = src.VoidTimestamp,
				trg.VoidUserIdentification = src.VoidUserIdentification
	WHEN NOT MATCHED BY TARGET
		THEN
			INSERT (
				Id,
				CreateTimestamp,
				UpdateTimestamp,
				TransportTimestamp,
				RequestInputTimestamp,
				RequestOutputTimestamp,
				AnswerInputTimestamp,
				AnswerOutputTimestamp,
				DeviceIdentification,
				LocationIdentification,
				ServiceName,
				OperationName,
				SequenceNumber,
				STATUS,
				UserIdentification,
				ProviderIdentification,
				ProviderTransactionID,
				DeviceTransactionID,
				SyncStatus,
				SyncTimestamp,
				ProductIdentification,
				RetrievalReferenceNumber,
				FacilitiesPayments,
				FacilitiesType,
				CurrencyCode,
				Amount,
				FeeAmount,
				TaxAmount,
				ComissionAmount,
				ServiceChargeAmount,
				MerchantIdentification,
				ProviderDeviceIdentification,
				ReverseStatus,
				ReverseTimestamp,
				VoidStatus,
				VoidTimestamp,
				VoidUserIdentification,
				RefundStatus,
				RefundTimestamp,
				RefundUserIdentification,
				RefundAmount,
				CloseStatus,
				CloseTimestamp,
				CloseUserIdentification,
				SettlementStatus,
				SettlementTimestamp,
				SettlementUserIdentification,
				SettlementAmount,
				SettlementTransactionId,
				RevisionStatus,
				RevisionTimestamp,
				RevisionReason,
				RevisionSource,
				BatchNumber,
				TicketNumber,
				ProviderBatchNumber,
				ProviderTicketNumber,
				ProviderTraceNumber,
				ProviderAuthorizationCode,
				CustomerIdentification,
				CredentialInputMode,
				CredentialMask,
				CredentialEncrypted,
				CredentialExpDate,
				CredentialCardHash,
				CredentialHolderName,
				CredentialAddress,
				CredentialDocumentType,
				CredentialDocumentNumber,
				CredentialEmailAddress,
				DeviceFingerprint,
				ResultCode,
				ResultMessage,
				ProviderResultCode,
				ProviderResultMessage,
				Channel,
				CaptureAddress,
				CaptureTimestamp,
				RequestAddress,
				RequestTimestamp,
				AnswerAddress,
				AnswerTimestamp,
				RedirectURLOK,
				RedirectURLError,
				CredentialBirthday,
				BillHolderName,
				BillHolderDocumentType,
				BillHolderDocumentNumber,
				ProviderCustomerCode,
				ProviderCustomerAdditionalCode,
				ChargeLatePaymentAmount,
				DifferenceBetweenFirstExpiration,
				DaysAfterFirstExpiration,
				CouponExpirationDate,
				InvoiceExpirationDate,
				PaymentBarCode,
				InvoiceBarCode,
				LiquidationStatus,
				LiquidationTimestamp,
				ReconciliationStatus,
				ReconciliationTimestamp,
				AvailableStatus,
				AvailableTimestamp,
				AvailableAmount,
				BillingStatus,
				BillingTimestamp,
				ProcessorResultCode,
				ProcessorResultMessage,
				ButtonId,
				ButtonExternalId,
				ButtonMinimumAmount,
				ButtonMaximumAmount,
				SaleConcept,
				MerchantActivityCode,
				ChargebackStatus,
				ChargebackTimestamp,
				ChargebackReason,
				CashoutStatus,
				CashoutTimestamp,
				FilingDeadline,
				PaymentDeadline,
				PaymentTimestamp,
				PaymentStatus,
				CouponStatus,
				CouponDaysBetweenExpDates,
				CouponValidityDays,
				CouponFee,
				CouponSecondExpirationDate,
				CouponClientCode,
				CouponSubscriber,
				CouponOperationId,
				OriginalOperationId,
				TransactionStatus,
				ProductType,
				BankIdentification,
				BuyerAccountIdentification,
				PrivateRequestKey,
				PublicRequestKey,
				PrivateAnswerKey,
				PublicAnswerKey,
				PublicIdentification,
				id_medio_pago_cuenta,
				AmountBuyer,
				FeeAmountBuyer,
				TaxAmountBuyer,
				PromotionIdentification,
				AdditionalData,
				FraudResultCode,
				FraudTransactionID,
				PresentationTimestamp,
				DocumentationTimestamp,
				DocumentationURL,
				PushNotifyMethod,
				PushNotifyEndpoint,
				PushNotifyStates,
				PushNotifySentTimestamp,
				PushNotifyCounter,
				Version,
				BuyerIP,
				SDK,
				SDKVersion,
				LenguageVersion,
				PluginVersion,
				ECommerceName,
				ECommerceVersion,
				CMSVersion,
				flag_formulario_cargado,
				CashoutReleaseStatus,
				CashoutReleaseTimestamp,
				MaxInstallments
				)
			VALUES (
				src.Id,
				src.CreateTimestamp,
				src.UpdateTimestamp,
				src.TransportTimestamp,
				src.RequestInputTimestamp,
				src.RequestOutputTimestamp,
				src.AnswerInputTimestamp,
				src.AnswerOutputTimestamp,
				src.DeviceIdentification,
				src.LocationIdentification,
				src.ServiceName,
				src.OperationName,
				src.SequenceNumber,
				src.STATUS,
				src.UserIdentification,
				src.ProviderIdentification,
				src.ProviderTransactionID,
				src.DeviceTransactionID,
				1,
				GETDATE(),
				src.ProductIdentification,
				src.RetrievalReferenceNumber,
				src.FacilitiesPayments,
				src.FacilitiesType,
				src.CurrencyCode,
				src.Amount,
				src.FeeAmount,
				src.TaxAmount,
				src.ComissionAmount,
				src.ServiceChargeAmount,
				src.MerchantIdentification,
				src.ProviderDeviceIdentification,
				src.ReverseStatus,
				src.ReverseTimestamp,
				src.VoidStatus,
				src.VoidTimestamp,
				src.VoidUserIdentification,
				src.RefundStatus,
				src.RefundTimestamp,
				src.RefundUserIdentification,
				src.RefundAmount,
				src.CloseStatus,
				src.CloseTimestamp,
				src.CloseUserIdentification,
				src.SettlementStatus,
				src.SettlementTimestamp,
				src.SettlementUserIdentification,
				src.SettlementAmount,
				src.SettlementTransactionId,
				src.RevisionStatus,
				src.RevisionTimestamp,
				src.RevisionReason,
				src.RevisionSource,
				src.BatchNumber,
				src.TicketNumber,
				src.ProviderBatchNumber,
				src.ProviderTicketNumber,
				src.ProviderTraceNumber,
				src.ProviderAuthorizationCode,
				src.CustomerIdentification,
				src.CredentialInputMode,
				src.CredentialMask,
				src.CredentialEncrypted,
				src.CredentialExpDate,
				src.CredentialCardHash,
				src.CredentialHolderName,
				src.CredentialAddress,
				src.CredentialDocumentType,
				src.CredentialDocumentNumber,
				src.CredentialEmailAddress,
				src.DeviceFingerprint,
				src.ResultCode,
				src.ResultMessage,
				src.ProviderResultCode,
				src.ProviderResultMessage,
				src.Channel,
				src.CaptureAddress,
				src.CaptureTimestamp,
				src.RequestAddress,
				src.RequestTimestamp,
				src.AnswerAddress,
				src.AnswerTimestamp,
				src.RedirectURLOK,
				src.RedirectURLError,
				src.CredentialBirthday,
				src.BillHolderName,
				src.BillHolderDocumentType,
				src.BillHolderDocumentNumber,
				src.ProviderCustomerCode,
				src.ProviderCustomerAdditionalCode,
				src.ChargeLatePaymentAmount,
				src.DifferenceBetweenFirstExpiration,
				src.DaysAfterFirstExpiration,
				src.CouponExpirationDate,
				src.InvoiceExpirationDate,
				src.PaymentBarCode,
				src.InvoiceBarCode,
				src.LiquidationStatus,
				src.LiquidationTimestamp,
				src.ReconciliationStatus,
				src.ReconciliationTimestamp,
				src.AvailableStatus,
				src.AvailableTimestamp,
				src.AvailableAmount,
				src.BillingStatus,
				src.BillingTimestamp,
				src.ProcessorResultCode,
				src.ProcessorResultMessage,
				src.ButtonId,
				src.ButtonExternalId,
				src.ButtonMinimumAmount,
				src.ButtonMaximumAmount,
				src.SaleConcept,
				src.MerchantActivityCode,
				src.ChargebackStatus,
				src.ChargebackTimestamp,
				src.ChargebackReason,
				src.CashoutStatus,
				src.CashoutTimestamp,
				src.FilingDeadline,
				src.PaymentDeadline,
				src.PaymentTimestamp,
				src.PaymentStatus,
				src.CouponStatus,
				src.CouponDaysBetweenExpDates,
				src.CouponValidityDays,
				src.CouponFee,
				src.CouponSecondExpirationDate,
				src.CouponClientCode,
				src.CouponSubscriber,
				src.CouponOperationId,
				src.OriginalOperationId,
				src.TransactionStatus,
				src.ProductType,
				src.BankIdentification,
				src.BuyerAccountIdentification,
				src.PrivateRequestKey,
				src.PublicRequestKey,
				src.PrivateAnswerKey,
				src.PublicAnswerKey,
				src.PublicIdentification,
				src.id_medio_pago_cuenta,
				src.AmountBuyer,
				src.FeeAmountBuyer,
				src.TaxAmountBuyer,
				src.PromotionIdentification,
				src.AdditionalData,
				src.FraudResultCode,
				src.FraudTransactionID,
				src.PresentationTimestamp,
				src.DocumentationTimestamp,
				src.DocumentationURL,
				src.PushNotifyMethod,
				src.PushNotifyEndpoint,
				src.PushNotifyStates,
				src.PushNotifySentTimestamp,
				src.PushNotifyCounter,
				src.Version,
				src.BuyerIP,
				src.SDK,
				src.SDKVersion,
				src.LenguageVersion,
				src.PluginVersion,
				src.ECommerceName,
				src.ECommerceVersion,
				src.CMSVersion,
				src.flag_formulario_cargado,
				src.CashoutReleaseStatus,
				src.CashoutReleaseTimestamp,
				src.MaxInstallments
				)
	OUTPUT src.Id
	INTO @MergeTable;

	UPDATE OpTrn
	SET OpTrn.SyncStatus = 1,
		OpTrn.SyncTimestamp = GETDATE()
	FROM Operations.dbo.transactions OpTrn
	INNER JOIN @MergeTable MgTrn
		ON OpTrn.Id = MgTrn.srcId;

	SET @registros_afectados = @@ROWCOUNT;

	-- Completar Log de Proceso   
	EXEC Configurations.dbo.Batch_Log_Finalizar_Proceso @id_log_proceso,
		@registros_afectados,
		@usuario;

	COMMIT TRANSACTION;

	RETURN 1;
END TRY

BEGIN CATCH
	IF (@@TRANCOUNT > 0)
		ROLLBACK TRANSACTION;

	THROW;

	RETURN 0;
END CATCH;
